# Generated by Django 3.1.1 on 2020-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_auto_20200929_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
