# Generated by Django 3.1.1 on 2020-09-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
