# Generated by Django 3.1.1 on 2020-09-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0006_blogmodel_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='BookModel',
        ),
    ]
